name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      apply_branch:
        description: 'Apply branch'
        required: true
        default: 'main'
        type: string

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform-apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Checkout base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.apply_branch }}

      - name: Init Terraform 
        run: |
          terraform init
          
      - name: Terraform apply
        run: |
          terraform apply -auto-approve